Myos 4 extended printf
Spieskowcy/MyOS pull request #4
Opened 2022-10-28 17:48 UTC by BognaLew

added options %d, %i, %x, %X, %p and %b (custom for printing binary numbers) to function printf. Also implemented functions itoa (convert integer to string), abs (absolute value), strrev (reverse string), strlwr (convert string to lowercase), strupr (convert string to uppercase).

2022-10-31 17:55 UTC, bstrzelecki approved these changes

2022-11-03 00:58 UTC, AaronWantoch commented on libc/stdio/printf.c
> +
?

2022-11-03 01:15 UTC, AaronWantoch reviewed
Some stylistic suggestions (no need to apply them). But I have one doubt.

2022-11-03 01:15 UTC, AaronWantoch commented on libc/stdlib/itoa.c
> +void split_to_numbers(unsigned int value, size_t * num_of_char, char* str, int base){
Can we stick to one convention of pointers (where do we put the *) 
```suggestion
void split_to_numbers(unsigned int value, size_t* num_of_char, char* str, int base){
```

2022-11-03 01:15 UTC, AaronWantoch commented on libc/string/strlwr.c
> +		if(64 < str[index] && str[index] < 91){
I would prefer it like that (my personal opinion)
```suggestion
		if(str[index] < 64 && str[index] < 91){
```

2022-11-03 01:15 UTC, AaronWantoch commented on libc/string/strupr.c
> +                if(96 < str[index] && str[index] < 123){
same as above
```suggestion
                if(str[index] > 96 && str[index] < 123){
```

2022-11-03 01:15 UTC, AaronWantoch commented on libc/stdlib/itoa.c
> +char get_ascii(int number){
I don't understand how it works, if it is number from 0-9 we convert it into char equivalent. and number 11 means A right? What about small letters there is a gap in ASCI between big and small case letters. 
Please elaborate
![image](https://user-images.githubusercontent.com/58564314/199630227-765e6a3e-7923-4201-9d43-fba00fd118c8.png)

2022-11-03 01:35 UTC, AaronWantoch requested changes
Stylistic changes may be ignored but please elaborate on get_ascii function

2022-11-03 01:35 UTC, AaronWantoch commented on libc/stdlib/itoa.c
> +char get_ascii(int number){
Can you elaborate on that function
I understand that number of value 0-9 will be converted into '0'-'9' and number of value 10 means 'A' and so on.
But what about small case letters? They start from value 97 and there is a gap between big case letters and small case letters.
![image](https://user-images.githubusercontent.com/58564314/199632156-1f5f75af-444e-4546-a967-2c8245e3e4f2.png)
If on the other hand we consider those signs (marked in yellow) what about signs with ASCI value 58-64.
From what I can see this function is unable to return them.
![image](https://user-images.githubusercontent.com/58564314/199632386-e96f08b7-4318-4a2b-90fd-c8e72147e4f7.png)

2022-11-03 01:35 UTC, AaronWantoch commented on libc/stdlib/itoa.c
> +void split_to_numbers(unsigned int value, size_t * num_of_char, char* str, int base){
Please stick to one convention of pointers (where we put '*' sign)
```suggestion
void split_to_numbers(unsigned int value, size_t* num_of_char, char* str, int base){
```

2022-11-03 01:35 UTC, AaronWantoch commented on libc/string/strlwr.c
> +		if(64 < str[index] && str[index] < 91){
I prefer it this way although it is my personal opinion
```suggestion
		if(str[index] > 64 && str[index] < 91){
```

2022-11-03 01:35 UTC, AaronWantoch commented on libc/string/strupr.c
> +                if(96 < str[index] && str[index] < 123){
same as above
```suggestion
                if(str[index] > 96 && str[index] < 123){
```

2022-11-03 10:14 UTC, AaronWantoch approved these changes

2022-11-03 10:20 UTC, merged